package json_to_go

import "testing"

func TestParse(t *testing.T) {
	result, err := Parse(testData)
	if err != nil {
		t.Fatal(err)
	}
	t.Log(result)
}

var (
	// https://api.github.com/repos/kumakichi/json-to-go
	testData = `{
  "xxx":3.0,
  "id": 250017396,
  "node_id": "MDEwOlJlcG9zaXRvcnkyNTAwMTczOTY=",
  "name": "json-to-go",
  "full_name": "kumakichi/json-to-go",
  "private": false,
  "owner": {
    "login": "kumakichi",
    "id": 1632587,
    "node_id": "MDQ6VXNlcjE2MzI1ODc=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/1632587?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kumakichi",
    "html_url": "https://github.com/kumakichi",
    "followers_url": "https://api.github.com/users/kumakichi/followers",
    "following_url": "https://api.github.com/users/kumakichi/following{/other_user}",
    "gists_url": "https://api.github.com/users/kumakichi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kumakichi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kumakichi/subscriptions",
    "organizations_url": "https://api.github.com/users/kumakichi/orgs",
    "repos_url": "https://api.github.com/users/kumakichi/repos",
    "events_url": "https://api.github.com/users/kumakichi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kumakichi/received_events",
    "type": "User",
    "site_admin": false
  },
  "html_url": "https://github.com/kumakichi/json-to-go",
  "description": "Translates JSON into a Go type(golang implementation of https://github.com/mholt/json-to-go)",
  "fork": false,
  "url": "https://api.github.com/repos/kumakichi/json-to-go",
  "forks_url": "https://api.github.com/repos/kumakichi/json-to-go/forks",
  "keys_url": "https://api.github.com/repos/kumakichi/json-to-go/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/kumakichi/json-to-go/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/kumakichi/json-to-go/teams",
  "hooks_url": "https://api.github.com/repos/kumakichi/json-to-go/hooks",
  "issue_events_url": "https://api.github.com/repos/kumakichi/json-to-go/issues/events{/number}",
  "events_url": "https://api.github.com/repos/kumakichi/json-to-go/events",
  "assignees_url": "https://api.github.com/repos/kumakichi/json-to-go/assignees{/user}",
  "branches_url": "https://api.github.com/repos/kumakichi/json-to-go/branches{/branch}",
  "tags_url": "https://api.github.com/repos/kumakichi/json-to-go/tags",
  "blobs_url": "https://api.github.com/repos/kumakichi/json-to-go/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/kumakichi/json-to-go/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/kumakichi/json-to-go/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/kumakichi/json-to-go/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/kumakichi/json-to-go/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/kumakichi/json-to-go/languages",
  "stargazers_url": "https://api.github.com/repos/kumakichi/json-to-go/stargazers",
  "contributors_url": "https://api.github.com/repos/kumakichi/json-to-go/contributors",
  "subscribers_url": "https://api.github.com/repos/kumakichi/json-to-go/subscribers",
  "subscription_url": "https://api.github.com/repos/kumakichi/json-to-go/subscription",
  "commits_url": "https://api.github.com/repos/kumakichi/json-to-go/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/kumakichi/json-to-go/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/kumakichi/json-to-go/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/kumakichi/json-to-go/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/kumakichi/json-to-go/contents/{+path}",
  "compare_url": "https://api.github.com/repos/kumakichi/json-to-go/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/kumakichi/json-to-go/merges",
  "archive_url": "https://api.github.com/repos/kumakichi/json-to-go/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/kumakichi/json-to-go/downloads",
  "issues_url": "https://api.github.com/repos/kumakichi/json-to-go/issues{/number}",
  "pulls_url": "https://api.github.com/repos/kumakichi/json-to-go/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/kumakichi/json-to-go/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/kumakichi/json-to-go/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/kumakichi/json-to-go/labels{/name}",
  "releases_url": "https://api.github.com/repos/kumakichi/json-to-go/releases{/id}",
  "deployments_url": "https://api.github.com/repos/kumakichi/json-to-go/deployments",
  "created_at": "2020-03-25T15:31:11Z",
  "updated_at": "2020-03-26T06:30:03Z",
  "pushed_at": "2020-03-26T00:18:55Z",
  "git_url": "git://github.com/kumakichi/json-to-go.git",
  "ssh_url": "git@github.com:kumakichi/json-to-go.git",
  "clone_url": "https://github.com/kumakichi/json-to-go.git",
  "svn_url": "https://github.com/kumakichi/json-to-go",
  "homepage": "",
  "size": 6,
  "stargazers_count": 1,
  "watchers_count": 1,
  "language": "Go",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "forks_count": 0,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 0,
  "license": null,
  "forks": 0,
  "open_issues": 0,
  "watchers": 1,
  "default_branch": "master",
  "temp_clone_token": null,
  "network_count": 0,
  "subscribers_count": 1
}`
)
